config/routes.rb
Rails.application.routes.draw do


  resources :categories
  resources :tags, only: [:show]
  resources :users, only: [:show]
  resource :users, only: [:update, :edit], path: 'user' do
    get :edit_password
    patch :update_password
  end
  root 'posts#index'
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end


  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' } # todo: убери потом измнения юзера из дивайса

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def commenter
    if user.present?
      user.name
    else
      'Anonymous'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy

  validates :title, :content, presence: true, length: { minimum: 5 }

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

end

app/models/taggable.rb
class Taggable < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy ]

  def index
    @categories = Category.all
  end
  def show
  end

  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, succes:"Категория создана"
    else
      flash[:danger] = "Категория не создана"
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      redirect_to categories_path, succes: "Категория обновлена"
    else
      flash[:dager] = 'Категория не обновлена'
      render :edit
    end
  end


  def destroy
    @category.destroy
    redirect_to categories_path, succes:"Категория удалена"
  end


  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :parent_id )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

    def post
      @post ||= Post.find(params[:post_id])
    end

    def comment_params
      params.require(:comment)
        .permit(:text)
        .merge(user_id: current_user.try(:id))
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id, :all_tags, :category_id )
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to current_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location:current_user }
      else
        format.html { render :edit }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    post = @user.posts
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password(password_params)
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render "edit_password"
    end
  end

  def edit
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email )
  end

  def password_params
    params.require(:user).permit(:password, :current_password )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
 <% if @category.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= t('common.errors') %></h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for (@category) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :parent_id %>
    <%= f.collection_select :parent_id, @categories, :id , :name, {iclude_blank:true}, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit t('.submit', action: @category.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1><%= t('.title') %></h1>

<div class= "buttons_panel">
  <%= link_to 'Новая категория', new_category_path, class: 'btn-btn-outline-primary btn-sn' %>
</div>

<section id = "categories" >
  <table class = "table"
    <thead>
      <tr>
        <th>#</th>
        <th>Название</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category,index| %>
        <tr>
         <td><%= index+1 %></td>
         <td><%= category.name %></td>
         <td>
           <%= link_to "Изменить" , edit_category_path(category),class: 'btn-btn-outline-primary btn-sn' %>
           <%= link_to "Удалить" , category_path(category), method: :delete , class: 'btn-btn-outline-danger btn-sn' %>
         </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newblog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded" >
      <div class="container"
        <ul class="nav navbar-nav" >
          <% if user_signed_in? %>
            <li>
              <%= link_to "Изменить профиль",    edit_users_path,  class: 'btn btn-outline-primary'   %>
            </li>
            <li>
              <%= link_to "Выйти", destroy_user_session_path, method: :delete,  class: 'btn btn-outline-primary'  %>
            </li>
            <li>
              <%= link_to "Все Посты", posts_path, class: 'btn btn-outline-primary' %>
            </li>
            <li>
              <%= link_to "Новый пост", new_post_path,  class: 'btn btn-outline-primary'  %>
            </li>
            <% else %>
            <li>
               <%= link_to "Регистрация", new_user_registration_path, class: 'btn btn-outline-primary' %>
            </li>
            <li>
              <%= link_to "Войти", new_user_session_path, class: 'btn btn-outline-primary pull-xs-right' %>
            </li>
            <li>
              <%= link_to "Все Посты", posts_path, class: 'btn btn-outline-primary' %>
            </li>
          <% end %>
        </ul>
    </div>
   </nav>


  <div class="container main">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name, message| %>
          <div class="alert alert-<%= name %>">
            <%= message %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-9">
        <%= yield %>
      </div>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= t('common.errors') %></h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for (post) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :all_tags %>
    <%= f.text_field :all_tags, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit t('.submit', action: @post.new_record? ? 'Создать' : 'Изменить'), class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
  <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %>
      </time>
      <%= link_to @post.category.name, @post.category if post.category.present? %>

      <%= link_to 'Удалить', post_path(post), method: :delet, data: { confirm: 'Вы уверены?'} %>
      <%= link_to 'Изменить', edit_post_path(post) %>
      <user><%= link_to post.user.name, user_path(post.user) %></user>
    </small>

  </section>
  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map{ |t| link_to t,  tag_path(t), class: 'tag tag-primary' }.join(' ') %>
  </section>
</article>

app/views/posts/edit.html.erb
 <h1><%= t('.title') %></h1>


<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1><%= t('.title')%></h1>

<%= render @posts %>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1><%= I18n.t('posts.new.title') %></h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<article class="post">
  <section class="post-head">
    <small>
    <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
    <%= link_to 'Изменить', edit_post_path(@post) %>
     <%= link_to @post.category.name, @post.category if @post.category.present? %>
    </small>
  </section>
</article>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <strong><%= comment.commenter %></strong>
    <%= comment.text %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text, class: 'form-control' %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Удалить', post_path(@post), method: :delete, data: { confirm: 'Вы уверены?'} %>

<%= link_to 'Изменить', edit_post_path(@post) %> |
<%= link_to 'Назад', post_path %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @Tags.each do |tag| %>
      <tr>
        <td><%= tag.tag %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% if @tag.posts.empty? %>
  <h2>Нет постов</h2>
<% else %>
  <%= render @tag.posts %>
<% end %>

app/views/users/_form.html.erb
 <% if user.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= t('common.errors') %></h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @user, url: users_path do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :password, "New password" %><br />
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
    <% end %>
    <%= f.password_field :password, autofocus: true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirm new password" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Change my password" %>
  </div>

  <div class="actions">
    <%= f.submit 'Изменить', class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

 <% if @user.errors.any? %>
  <div class="alert alert-danger">
    <h2><%= t('common.errors') %></h2>

    <ul>
      <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @user, url: users_path do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
<% end %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/users/edit_password.erb
<h2>Change your password</h2>

<%= form_for @user, url: update_password_users_path do |f| %>
  <div class="field">
    <%= f.label :current_password, "Current password" %><br />
    <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em><br />
    <% end %>
    <%= f.password_field :current_password, autofocus: true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit 'Изменить', class: 'btn btn-primary' %>
    <%= link_to t('common.back'), :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if @user.posts.empty? %>
  <h2>Нет постов</h2>
<% else %>
  <%= render @user.posts %>
<% end %>